"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MainWindow.py']
APP_Name = 'Calculator'
DATA_FILES = ['Xiaojianpan.py','BiaodaShi.py']
OPTIONS = {
    'argv_emulation': True,
    'includes':['tkinter', 'operator', 'math', 'sip'],
    'iconfile': 'Calculator.icns',
    'plist':{
        'CFBundleNamw': APP_Name,
        'CFBundleDisplayName': APP_Name,
        'CFBundleVersion': '2019.2.0',
        'CFBundleShortVersion': '2.0',
        'NSHumanReadableCopyright': u'Copyright ©2019.08.01. Written by Chongjie Si, All Rights Reserved.'
        }
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
